linters:
  enable-all: true
  disable:
    - wsl
    - varnamelen
    - nonamedreturns
    - nlreturn
    - tenv
    - gochecknoglobals
    - funlen
    - paralleltest
    - mnd
    - gochecknoinits
    - cyclop
    - exhaustruct
    - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
