// SPDX-License-Identifier: BSD-2-Clause
// SPDX-FileCopyrightText: Copyright (c) 2025 Runxi Yu <https://runxiyu.org>

package main

// global is a struct that holds global information that the HTML template may
// wish to access.
var global = struct {
	// Most of these fields should be filled in by flag parsing.
	NeedBits        uint
	NeedBitsReverse uint
	SourceURL       string
	Version         string
}{
	// The version should be replaced by the init function in version.go,
	// if version.go is properly generated by the Makefile.
	Version: "(no version)",
}
